/* Build one authoring spec per course from the skeleton + per-course context. */
const fs = require('fs');
const path = require('path');

const skel = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'ai-engineering-skeleton.json'), 'utf8'));

const CTX = {
  'IR 100: Index Structures & Algorithms': 'Foundational data structures for search and data systems. Emphasize: cost-model thinking (Big-O of scan/probe/merge, why sequential beats random access), heaps for top-k, external merge sort as THE index-construction primitive, and greedy graph proximity search as the seed of HNSW (taught later in IR 201). Repair a weak DSA base rigorously but efficiently.',
  'DE 101: SQL & Relational Thinking': 'SQL from absolute zero to reading execution plans. Favor predict-the-output, choose-the-query, spot-the-bug examples. Center window functions, join fan-out pitfalls, and query plans. Bridge topics: B-tree index vs inverted search index; ACID and OLTP-vs-OLAP as workload categories.',
  'IR 101: Retrieval Foundations & Index Construction': 'The inverted index end to end (Manning/Raghavan/Schutze chs 1-2,4,5 territory). Teach text processing as DECISION scenarios (when stemming hurts precision, stop words vs phrase queries). Index construction: blocked builds + merging (lean on external merge sort from IR 100), logarithmic merge for dynamic updates. Compression essentials only: delta gaps + variable-byte; the "Postings Compression vs Parquet Encodings" topic is a deliberate bridge that DE 201 reactivates.',
  'IR 102: Corpus Acquisition & Web Data': "The collection side of the learner's research system: crawler architecture (frontier, politeness, traps), discovery (sitemaps, feeds, search APIs as acquisition), content extraction quality, freshness (change-rate modeling, recrawl priority, recency fused into ranking), and source quality (PageRank as a quality prior in ONE topic, spam detection, dedup POLICY only - mechanics live in DE 301, source credibility for a research corpus).",
  'IR 103: Ranking I - Vector Space & tf-idf': "From matching to ranking. tf saturation, idf as rarity signal, cosine similarity built directly on the learner's linear algebra, document length normalization, and efficient top-k (term-at-a-time vs document-at-a-time, index elimination/champion lists, WAND/MaxScore).",
  'IR 104: IR Evaluation': 'Extend the learner\'s mastered set-based precision/recall/F1 to RANKED retrieval: P@k/R@k, AP/MAP, MRR, nDCG (what changes when ranking and graded relevance enter). Frame test collections as "build your own golden query set" for production reuse (regression canaries return in DE 401). Include LLM-as-relevance-judge uses and failure modes; MS MARCO/BEIR descriptively.',
  'IR 105: Ranking II - Probabilistic Models & BM25': "The crown derivation course: Probability Ranking Principle -> Binary Independence Model -> RSJ weight -> BM25, DERIVED step by step using the learner's strong probability (odds, Bayes, independence assumptions). k1 = term-frequency saturation, b = length normalization; then query-likelihood language models and why smoothing is mandatory (Jelinek-Mercer vs Dirichlet), and Rocchio/pseudo-relevance feedback/RM3 as the classical ancestor of modern query expansion.",
  'DE 102: Data Modeling for Analytics & Retrieval': 'One modeling discipline, two shapes. Normalization/denormalization (incl. STRUCT/ARRAY nested-repeated fields as the modern denormalization endpoint), facts/dimensions and GRAIN, star vs snowflake, SCD Type 2. Then the corpus data model: documents/chunks/embeddings as modeling grains, chunking AS a grain decision (same question as "what does one row represent"), content addressing via hashing, lineage that makes citations possible. Teach SCD2 and document versioning as the SAME idea.',
  'DE 201: Storage Layout & Table Formats': 'Where compute savings live. Parquet internals (row groups, column chunks, encodings, column stats, predicate pushdown), codecs ratio-vs-speed, partitioning and pruning, the small-file problem and compaction (echo LSM merging from IR 101), object storage semantics (immutability, consistency limits), and open table formats (Iceberg/Delta): ACID via metadata layers, snapshots/time travel, schema evolution rules, safe backfills, and atomic rebuild-and-swap as an INTRO (the operational playbook lives in DE 401). Reactivate the postings-compression bridge from IR 101.',
  'DE 202: ETL & Pipeline Engineering': 'Idempotency is the center of gravity of the whole track. ETL vs ELT, zones, data contracts; idempotent writes, deterministic partitioning, incremental vs full refresh; the Beam model (PCollections, transforms, shuffles, what/where/when/how); streaming semantics at PDE-exam depth: windowing types, watermarks and late data, triggers and accumulation modes, exactly-once vs at-least-once vs effectively-once, Pub/Sub acks/ordering keys/dead-letter queues; CDC log-based vs query-based; orchestration (DAGs, retries, backfill runs, Airflow/Composer vs Workflows, validation gates, CI/CD for pipelines).',
  'IR 201: Semantic & Dense Retrieval': "The vocabulary mismatch problem and its neural fix. LSA in exactly ONE bridge topic (SVD on the term-doc matrix -> the learner's PCA/eigenvalue mastery). Bi-encoders as dual towers (SAME architecture as the recommenders the learner mastered). ANN indexes: IVF as k-means partitioning (their k-means, literally), HNSW as layered greedy graph search (bridge to IR 100 graphs lesson), product quantization, the recall/latency/memory triangle. Then the engineer's lesson: contrastive training, in-batch vs hard negatives, fine-tuning embedders, MTEB and instruction-tuned models, Matryoshka truncation, scalar/binary quantization as recall-per-dollar.",
  'IR 202: Multi-stage Ranking & Hybrid Retrieval': 'The production funnel the learner already ships, formalized. Recall stage vs precision stage and candidate budgeting; cross-encoders (joint attention) vs bi-encoders and rerank depth; hybrid fusion: WHY sparse and dense fail differently, reciprocal rank fusion vs score normalization, and "The Atrium Pattern" topic = the learner\'s own production architecture (BM25 + dense vectors + RRF + reranker) analyzed as a general pattern; learned sparse retrieval (SPLADE term expansion + impact weights, doc2query document expansion, impact-sorted indexes, shipped systems like ELSER/neural sparse) framed as neural models running on the SAME inverted index from IR 101; late interaction (ColBERT token-level matching, PLAID serving) and cross-encoder distillation as one "beyond the cross-encoder" lesson.',
  'IR 301: Retrieval for LLMs': "Retrieval as the context layer of LLM systems - the generation side of the learner's goal. Chunking tradeoffs (size/overlap, structure-aware, contextual enrichment); context assembly (selection/ordering, citation-grounded span attribution, metadata filters APPLIED here - mechanics in DE 301, window budgeting: relevance density over volume); the agentic lesson (single-shot rewriting/expansion/HyDE compressed to one topic, retrieval-as-a-tool loops with decide-to-stop policies, query decomposition/multi-hop, conversational rewriting across turns, self-correcting RAG, text-to-SQL as a retrieval tool); RAG evaluation (faithfulness, context precision/recall, answer relevance, RAGAS/DeepEval/TruLens landscape and the LLM-judge pitfall); RAG security (ACL-aware retrieval, tenant isolation in shared indexes, prompt injection via retrieved content - the learner runs a multi-tenant production system); latency/cost engineering (the retrieve/rerank/generate budget, caching layers, long-context vs retrieval).",
  'DE 301: Data for ML & Retrieval Pipelines': 'Data correctness for ML plus text-pipeline construction. Feature pipelines and stores (offline training vs online serving), point-in-time correctness and time-travel joins, label leakage, training-serving skew, dataset versioning; parsing/extraction as pipeline stages, MinHash/SimHash and LSH mechanics for near-duplicate detection (the mechanics IR 102 deferred), language ID and quality filtering; chunk-and-embed as an idempotent batch job, vectors beside metadata, pre-filter vs post-filter ANN; vector databases as a product category (index types by OPERATIONAL profile, sync with the source of truth as the real hard problem, when you do not need one).',
  'DE 302: GCP Data Engineering Stack': 'The Professional Data Engineer certification course, organized by exam domain. Frame EVERY service as "which concept from earlier courses does this implement". Storage/database selection as a workload-driven decision matrix (Cloud SQL vs AlloyDB vs Spanner; Firestore vs Bigtable vs Memorystore; GCS classes/lifecycle; Datastream/DMS/BigQuery Data Transfer/Transfer Appliance); BigQuery internals (storage-compute separation, partitioning/clustering, Editions + reservations + slot autoscaling, on-demand vs capacity pricing); the BigQuery analysis+AI layer (materialized views, BI Engine, query troubleshooting, BigQuery ML at awareness level, ML.GENERATE_EMBEDDING and native VECTOR_SEARCH, preparing unstructured data for embeddings/RAG); ingestion/streaming services (Pub/Sub semantics, Dataflow in production, Datastream CDC, Kafka-vs-Pub/Sub awareness); transformation/orchestration (Dataform dependency graphs, Data Fusion awareness, Composer vs Workflows selection criterion); lakehouse/governance (BigLake, Dataplex + catalog, Analytics Hub sharing); security/compliance (IAM roles/service accounts/org policies, CMEK/KMS, Cloud DLP PII masking, residency, project/dataset architecture); operate/optimize (monitoring/logging, quotas/billing troubleshooting, Dataproc persistent-vs-ephemeral with Hadoop/Spark at awareness, replication/failover/backup-DR, drawing the certification-ready reference architecture). Teach stable service SEMANTICS and decision frameworks as of early 2026; prefer principles over console UI details.',
  'DE 401: Capstone - The LLM Data Backbone': 'Pure judgment synthesis of the whole curriculum - scenario-heavy. End-to-end architecture (source -> ingestion -> lake -> feature store -> index -> RAG endpoint; batch vs streaming paths; component contracts; source-of-truth vs derived copies); observability (freshness SLAs and lag, production hit rate/MRR/reranker score monitoring, golden query sets as regression canaries, triaging quality drops: data drift vs index defect vs model change); cost engineering (hot/cold tiering, precompute vs compute-on-read, quantization recall-per-dollar, re-embedding cadence); the re-embedding/backfill playbook (rebuild-and-swap with versioned aliases, shadow index validation gates, incremental vs full backfill triggers, rollback and mixed-version serving risks); scenario diagnosis (symptom-to-layer triage, latency budget breakdown, defending design choices under constraints). Ground everything in realistic incident narratives with numbers.',
};

const CODE = (course) => course.split(':')[0].replace(/\s+/g, ''); // "IR 100: X" -> "IR100"

const outDir = path.join(__dirname, 'specs');
fs.mkdirSync(outDir, { recursive: true });
for (const c of skel.courses) {
  const spec = {
    track: c.track,
    course: c.course,
    context: CTX[c.course] || '',
    lessons: c.lessons.map((l, i) => ({
      index: String(i + 1).padStart(2, '0'),
      lesson: l.lesson,
      topics: l.topics,
      alreadyTaughtInCourse: c.lessons.slice(0, i).flatMap((x) => x.topics),
      laterLessonsCover: c.lessons.slice(i + 1).map((x) => `${x.lesson}: ${x.topics.join(', ')}`),
    })),
  };
  fs.writeFileSync(path.join(outDir, `spec-${CODE(c.course)}.json`), JSON.stringify(spec, null, 1));
  console.log(`spec-${CODE(c.course)}.json  (${c.lessons.length} lessons, ${c.lessons.reduce((s, l) => s + l.topics.length, 0)} topics)`);
}
